[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.125.1"

[context.deploy-preview]
  command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.1"
